prop:
  FIRST_NAME: FirstName - Ramanan.. name is coming from local profile
  MIDDLE_NAME: MiddleName - Ramanan.. name is coming from local profile
  LAST_NAME: LastName - Ramanan.. name is coming from local profile



server:
  port: 8082